#!/bin/sh
#
# description: Starts and stops the jcontroller daemon
#
### BEGIN INIT INFO
# Provides: jcontroller
# Required-Start: $network $syslog
# Required-Stop: $network
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Short-Description: jcontroller daemon
# Description: Start or stop the jcontroller daemon
### END INIT INFO

BINARY=/home/pi/wifi-controller/jcontroller.py
test -x $BINARY || { echo "$BINARY not avaible";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }

RETVAL=0

case "$1" in
  start)
        echo -n "Starting jcontroller daemon... "
        cd /home/pi/wifi-controller
        sudo -u pi python3 -u 2>&1 >/home/pi/wifi-controller/jcontroller.log $BINARY &
        echo "Done."
        ;;
  stop)
        echo -n "Shutting down jcontroller daemon... "
        pkill -9 -f "python3 -u $BINARY"
        echo "Done."
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  status)
        if pgrep -f "python3 -u $BINARY" >/dev/null 2>&1
        then
          echo "jcontroller is running."
        else
          echo "jcontroller is not running."
        fi
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

