#!/bin/sh
#
# description: Starts and stops the PyROS daemon
#
### BEGIN INIT INFO
# Provides: PyROS
# Required-Start: $network $syslog $remote_fs mosquitto ssh bluetooth rc.local
# Required-Stop: $network
# Default-Start: 2 3 5
# Default-Stop: 0 1 6
# Short-Description: PyROS daemon
# Description: Start or stop the PyROS daemon
### END INIT INFO

BINARY=/home/pi/pyros/pyros-core.py
test -x $BINARY || { echo "$BINARY not avaible";
        if [ "$1" = "stop" ]; then exit 0;
        else exit 5; fi; }

RETVAL=0

case "$1" in
  start)
        echo -n "Starting PyROS daemon... "
        mkdir -p /home/pi/pyros/code
        mkdir -p /home/pi/pyros/logs
        chown pi /home/pi/pyros/code
        chown pi /home/pi/pyros/logs
        cd /home/pi/pyros/code
        sudo -u pi python3 -u 2>&1 >/home/pi/pyros/logs/pyros.log $BINARY &
        echo "Done."
        ;;
  stop)
        echo -n "Shutting down PyROS daemon... "
        pkill -9 -f "python3 -u $BINARY"
        echo "Done."
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  status)
        if pgrep -f "python3 -u $BINARY" >/dev/null 2>&1
        then
          echo "PyROS is running."
        else
          echo "PyROS is not running."
        fi
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1
esac

